# Generated by Django 4.0.1 on 2022-01-22 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0003_alter_itemcolor_options_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='brand',
            field=models.CharField(choices=[('나이키', '나이키'), ('디올', '디올'), ('아디다스', '아디다스'), ('구찌', '구찌')], default='나이키', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='nation',
            field=models.CharField(choices=[('미국', '미국'), ('일본', '일본'), ('중국', '중국'), ('홍콩', '홍콩'), ('유럽', '유럽')], default='미국', max_length=20),
        ),
    ]
