# Generated by Django 4.0.1 on 2022-01-22 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_nation_alter_room_nation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='nation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='rooms.nation'),
        ),
    ]
